spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: 127.0.0.1:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id:
        id:
          signal: signal-consumer-group-id
          distance: distance-consumer-group-id
      properties:
        spring:
          json:
            trusted:
              packages: org.example.kafkavehiclesignalstracking.model

kafka:
  topic:
    input: signal
    output: distance
